### ISSUE TITLE
instacart store ?

### ISSUE THREAD

**Issue by carefulcomputer** [jvkumar/delivery-finder#35]
Instacart has multiple stores.. is there any way to figure out which store has availability ?

**Comment by jvkumar** [comment]
AFAIK instacart doesn't show the delivery slot differently for stores. They have shoppers who are available to go to many stores and shop on your behalf. It is about the availability of shoppers, not of the store.

**Comment by carefulcomputer** [comment]
nope. i verified that (atleast for me) time slot availability changes based on store. i found a better url to check which has store name in it..

`https://www.instacart.com/v3/containers/<storename>/next_gen/retailer_information/content/delivery?source=web`

replace storename with 'foodmaxx', 'safeway' etc. and you will get different availability.

**Comment by jvkumar** [comment]
Oh, that's good to know. Thanks for finding it and correcting me 👍   
If you like to introduce `store-wise` availability to help people find specific store availability in this codebase, then feel free to send a PR. 
But at the current COVID-19 situation, I believe people are more concerned about finding the items in their cart (you can add multiple stores' items in a single cart ) than being specific about a store.

**Comment by carefulcomputer** [comment]
I have been using instacart heavily, and in my experience each store (at least in SF bay area) has it's own minimum and things vary by store. I have to pick the store first and then add items available from that store to cart. i.e i can't just add 'milk' and have it delivered from any of stores. i have to pick a store and select item's from store's selection. 
In addition, let's say if you add $10 items from  4 different stores then it still may not meet minimum since each store has it's own minimum order requirement. Time delivery for each store is also separate. It is as if there are 4 independent orders from 4 different stores, just in same cart. So at least for us here, we have to buy per store.

**Comment by carefulcomputer** [comment]
btw, i wrote some code of mine which takes care of login and store selection too (no need to copy paste the cookies).
Feel free to use.

https://github.com/qwertangel/instacart

**Comment by jvkumar** [comment]
👍
